[tool.poetry]
name = "diversity"
version = "0.1.0"
description = ""
authors = ["Chantal Shaib <shaib.c@northeastern.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
